<a href="https://colab.research.google.com/github/potopaa/ml_course_HWs/blob/addition%2Fnew_HW/HW_2_3_%D0%9C%D0%B0%D1%82%D1%80%D0%B8%D1%86%D1%96_%D1%96_%D0%B2%D0%B5%D0%BA%D1%82%D0%BE%D1%80%D0%B8_(%D0%B2%D1%81%D1%82%D1%83%D0%BF_%D0%B4%D0%BE_%D0%BB%D1%96%D0%BD_%D0%B0%D0%BB%D0%B3%D0%B5%D0%B1%D1%80%D0%B8).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### Завдання 1: Створення матриць та векторів
1. Створіть `numpy` вектор `vector` розмірністю 10 з випадковими дійсними значеннями в діапазоні від 0 до 1. Можна скористатись двома альтернативними варіантами:
  1. Генерація випадкових чисел з модулем [`random.uniform`](https://docs.python.org/3/library/random.html).
  2. Створення вектора з допомогою метода `numpy` [np.random.rand](https://numpy.org/doc/stable/reference/random/generated/numpy.random.rand.html)

2. Створіть матрицю `matrix` типу `numpy.array` розмірності 3x3 з наступними значеннями

  $$
  matrix = \begin{bmatrix}
  11 & 14 & 17 \\
  20 & 23 & 26 \\
  29 & 32 & 35
  \end{bmatrix}
  $$

  будь-яким відомими Вам способом.

Виведіть на екран вектор і матрицю, а також їх розміри.


### HW 1.1.

In [51]:
import random
import numpy as np

In [52]:
vector_uniform = np.array([random.uniform(0, 1) for i in range(10)])
vector_uniform, vector_uniform.shape

(array([0.56648528, 0.19342757, 0.20739586, 0.50089454, 0.52048356,
        0.17525311, 0.31518974, 0.11300583, 0.06205811, 0.7285204 ]),
 (10,))

In [53]:
vector_rand = np.random.rand(10)
vector_rand, vector_rand.shape

(array([0.44807341, 0.31862186, 0.75560187, 0.306049  , 0.9878636 ,
        0.01841007, 0.855241  , 0.85415026, 0.43345461, 0.45974074]),
 (10,))

###HW 1.2.


In [54]:
A = np.array([[11, 14, 17],
                   [20, 23, 26],
                   [29, 32, 35]])
A, A.shape

(array([[11, 14, 17],
        [20, 23, 26],
        [29, 32, 35]]),
 (3, 3))

In [55]:
AssertionError = [[11, 14, 17],
          [20, 23, 26],
          [29, 32, 35]]
A = np.array(A)
A, A.shape

(array([[11, 14, 17],
        [20, 23, 26],
        [29, 32, 35]]),
 (3, 3))

In [56]:
A = np.zeros((3, 3), dtype=int)
A[0, :] = [11, 14, 17]
A[1, :] = [20, 23, 26]
A[2, :] = [29, 32, 35]
A, A.shape

(array([[11, 14, 17],
        [20, 23, 26],
        [29, 32, 35]]),
 (3, 3))

In [57]:
A = np.matrix([[11, 14, 17],
                   [20, 23, 26],
                   [29, 32, 35]])
A, A.shape

(matrix([[11, 14, 17],
         [20, 23, 26],
         [29, 32, 35]]),
 (3, 3))

In [58]:
array = np.array([11, 14, 17, 20, 23, 26, 29, 32, 35])
A = array.reshape((3, 3))
A, A.shape

(array([[11, 14, 17],
        [20, 23, 26],
        [29, 32, 35]]),
 (3, 3))


### Завдання 2: Операції над векторами та матрицями
Виконайте кожну з зазначених операцій над зазначеними оʼєктами і виведіть результат на екран:
1. Додайте до кожного значення вектора `vector` число 10 і округліть кожне значення до 2 знаків після коми без використання циклів.
2. Помножте кожен елемент матриці з першого завдання на 2 без використання циклів.
3. Створіть новий вектор, який містить квадрат кожного `vector` без циклів.


In [59]:
vector_uniform_plus_10 = np.round(vector_uniform + 10, 2)
vector_uniform_plus_10

array([10.57, 10.19, 10.21, 10.5 , 10.52, 10.18, 10.32, 10.11, 10.06,
       10.73])

In [60]:
vector_rand_plus_10 = np.round(vector_rand + 10, 2)
vector_rand_plus_10

array([10.45, 10.32, 10.76, 10.31, 10.99, 10.02, 10.86, 10.85, 10.43,
       10.46])

In [61]:
A_times_2 = A * 2
A_times_2

array([[22, 28, 34],
       [40, 46, 52],
       [58, 64, 70]])

In [62]:
vector_squared = np.square(vector_uniform)
vector_squared

array([0.32090557, 0.03741423, 0.04301304, 0.25089534, 0.27090313,
       0.03071365, 0.09934457, 0.01277032, 0.00385121, 0.53074198])

In [63]:
vector_squared = np.square(vector_rand)
vector_squared

array([2.00769782e-01, 1.01519889e-01, 5.70934180e-01, 9.36659888e-02,
       9.75874487e-01, 3.38930559e-04, 7.31437173e-01, 7.29572665e-01,
       1.87882896e-01, 2.11361548e-01])


### Завдання 3: Множення матриць
1. Задані дві матриці `A` і `B`розмірностями 3x2 та 2х3. Виконайте їхнє множення, щоб отримати матрицю 2x2. Виведіть результуючу матрицю `result_matrix` на екран.

2. Заданий вектор `C` розмірністю 2х1. Подумайте спочатку, яку розмірність Ви отрмаєте, коли домножите `result_matrix` на вектор `C` і який результат буде. А потім виконайте множення і виведіть результат на екран.

3. Задана матриця `D` розмірністю 2х2. Подумайте спочатку, яку розмірність Ви отрмаєте, коли домножите `result_matrix` на матрицю `D` і який результат буде. А потім виконайте множення і виведіть результат на екран.

In [64]:
A = np.array(
    [[0.18, 0.53],
     [0.75, 0.47],
     [0.35, 0.21]])

B = np.array(
    [[0.17, 0.58, 0.75],
     [0.38, 0.11, 0.15]])

C = np.array([[0], [1]])

D = np.array([[0,1], [1,0]])

display(A, B, C, D)

array([[0.18, 0.53],
       [0.75, 0.47],
       [0.35, 0.21]])

array([[0.17, 0.58, 0.75],
       [0.38, 0.11, 0.15]])

array([[0],
       [1]])

array([[0, 1],
       [1, 0]])

### HW
Щоб від множення матриць А і В розмірностями 3х2 і 2х3 отримати матрицю 2х2 треба множити В на А:

In [65]:
result_matrix = np.dot(B, A)
result_matrix

array([[0.7281, 0.5202],
       [0.2034, 0.2846]])

In [66]:
C = np.array([[0], [1]])
result_vector = np.dot(result_matrix, C)
result_vector, result_vector.shape

(array([[0.5202],
        [0.2846]]),
 (2, 1))

In [67]:
result = np.dot(result_matrix, D)
result

array([[0.5202, 0.7281],
       [0.2846, 0.2034]])


### Завдання 4: Транспонування матриць
1. Транспонуйте `result_matrix`.
2. Зробіть транспонування вектора `vector` і виведіть форму нової структури. Чи бачите ви зміну?
3. Використайте операцію `numpy.expand_dims` над вектором `vector` з аргументом axis=1. Запишіть отриманий результат в змінну `column_vector` і виведіть на екран. Порівняйте з `vector`.
4. Зробіть транспонування `column_vector`, виведіть результат на екран разом з розмірностями отриманої структури.




In [68]:
result_matrix.T

array([[0.7281, 0.2034],
       [0.5202, 0.2846]])

In [69]:
vector_rand.T, vector_rand.T.shape

(array([0.44807341, 0.31862186, 0.75560187, 0.306049  , 0.9878636 ,
        0.01841007, 0.855241  , 0.85415026, 0.43345461, 0.45974074]),
 (10,))

In [70]:
vector_rand, vector_rand.shape

(array([0.44807341, 0.31862186, 0.75560187, 0.306049  , 0.9878636 ,
        0.01841007, 0.855241  , 0.85415026, 0.43345461, 0.45974074]),
 (10,))

In [71]:
transposed_vector = np.transpose(vector_rand)
transposed_vector, transposed_vector.shape

(array([0.44807341, 0.31862186, 0.75560187, 0.306049  , 0.9878636 ,
        0.01841007, 0.855241  , 0.85415026, 0.43345461, 0.45974074]),
 (10,))

In [72]:
column_vector = np.expand_dims(vector_rand, axis=1)
column_vector, column_vector.shape

(array([[0.44807341],
        [0.31862186],
        [0.75560187],
        [0.306049  ],
        [0.9878636 ],
        [0.01841007],
        [0.855241  ],
        [0.85415026],
        [0.43345461],
        [0.45974074]]),
 (10, 1))

In [73]:
trans_vector = np.transpose(column_vector)
trans_vector, trans_vector.shape

(array([[0.44807341, 0.31862186, 0.75560187, 0.306049  , 0.9878636 ,
         0.01841007, 0.855241  , 0.85415026, 0.43345461, 0.45974074]]),
 (1, 10))

In [75]:
column_vector.T, column_vector.T.shape

(array([[0.44807341, 0.31862186, 0.75560187, 0.306049  , 0.9878636 ,
         0.01841007, 0.855241  , 0.85415026, 0.43345461, 0.45974074]]),
 (1, 10))