<a href="https://colab.research.google.com/github/potopaa/ml_course_HWs/blob/addition%2Fnew_HW/HW_2_3_%D0%9C%D0%B0%D1%82%D1%80%D0%B8%D1%86%D1%96_%D1%96_%D0%B2%D0%B5%D0%BA%D1%82%D0%BE%D1%80%D0%B8_(%D0%B2%D1%81%D1%82%D1%83%D0%BF_%D0%B4%D0%BE_%D0%BB%D1%96%D0%BD_%D0%B0%D0%BB%D0%B3%D0%B5%D0%B1%D1%80%D0%B8).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### Завдання 1: Створення матриць та векторів
1. Створіть `numpy` вектор `vector` розмірністю 10 з випадковими дійсними значеннями в діапазоні від 0 до 1. Можна скористатись двома альтернативними варіантами:
  1. Генерація випадкових чисел з модулем [`random.uniform`](https://docs.python.org/3/library/random.html).
  2. Створення вектора з допомогою метода `numpy` [np.random.rand](https://numpy.org/doc/stable/reference/random/generated/numpy.random.rand.html)

2. Створіть матрицю `matrix` типу `numpy.array` розмірності 3x3 з наступними значеннями

  $$
  matrix = \begin{bmatrix}
  11 & 14 & 17 \\
  20 & 23 & 26 \\
  29 & 32 & 35
  \end{bmatrix}
  $$

  будь-яким відомими Вам способом.

Виведіть на екран вектор і матрицю, а також їх розміри.


### HW 1.1.

In [1]:
import random
import numpy as np

In [2]:
vector_uniform = np.array([random.uniform(0, 1) for i in range(10)])
vector_uniform, vector_uniform.shape

(array([0.56570288, 0.48451874, 0.28861134, 0.63479747, 0.83859617,
        0.83634501, 0.76241482, 0.12127395, 0.33946058, 0.13699544]),
 (10,))

In [3]:
vector_rand = np.random.rand(10)
vector_rand, vector_rand.shape

(array([0.83388667, 0.63979008, 0.40158324, 0.23699772, 0.09817857,
        0.05411366, 0.68022847, 0.87726471, 0.53101839, 0.7445003 ]),
 (10,))

###HW 1.2.


In [4]:
A = np.array([[11, 14, 17],
                   [20, 23, 26],
                   [29, 32, 35]])
A, A.shape

(array([[11, 14, 17],
        [20, 23, 26],
        [29, 32, 35]]),
 (3, 3))

In [5]:
A = [[11, 14, 17],
          [20, 23, 26],
          [29, 32, 35]]
A = np.array(A)
A, A.shape

(array([[11, 14, 17],
        [20, 23, 26],
        [29, 32, 35]]),
 (3, 3))

In [6]:
A = np.zeros((3, 3), dtype=int)
A[0, :] = [11, 14, 17]
A[1, :] = [20, 23, 26]
A[2, :] = [29, 32, 35]
A, A.shape

(array([[11, 14, 17],
        [20, 23, 26],
        [29, 32, 35]]),
 (3, 3))

In [7]:
A = np.matrix([[11, 14, 17],
                   [20, 23, 26],
                   [29, 32, 35]])
A, A.shape

(matrix([[11, 14, 17],
         [20, 23, 26],
         [29, 32, 35]]),
 (3, 3))

In [8]:
array = np.array([11, 14, 17, 20, 23, 26, 29, 32, 35])
A = array.reshape((3, 3))
A, A.shape

(array([[11, 14, 17],
        [20, 23, 26],
        [29, 32, 35]]),
 (3, 3))


### Завдання 2: Операції над векторами та матрицями
Виконайте кожну з зазначених операцій над зазначеними оʼєктами і виведіть результат на екран:
1. Додайте до кожного значення вектора `vector` число 10 і округліть кожне значення до 2 знаків після коми без використання циклів.
2. Помножте кожен елемент матриці з першого завдання на 2 без використання циклів.
3. Створіть новий вектор, який містить квадрат кожного `vector` без циклів.


In [9]:
vector_uniform_plus_10 = np.round(vector_uniform + 10, 2)
vector_uniform_plus_10

array([10.57, 10.48, 10.29, 10.63, 10.84, 10.84, 10.76, 10.12, 10.34,
       10.14])

In [10]:
vector_rand_plus_10 = np.round(vector_rand + 10, 2)
vector_rand_plus_10

array([10.83, 10.64, 10.4 , 10.24, 10.1 , 10.05, 10.68, 10.88, 10.53,
       10.74])

In [11]:
A_times_2 = A * 2
A_times_2

array([[22, 28, 34],
       [40, 46, 52],
       [58, 64, 70]])

In [12]:
vector_squared = np.square(vector_uniform)
vector_squared

array([0.32001975, 0.23475841, 0.0832965 , 0.40296783, 0.70324354,
       0.69947298, 0.58127636, 0.01470737, 0.11523349, 0.01876775])

In [13]:
vector_squared = np.square(vector_rand)
vector_squared

array([0.69536698, 0.40933134, 0.1612691 , 0.05616792, 0.00963903,
       0.00292829, 0.46271078, 0.76959337, 0.28198053, 0.5542807 ])


### Завдання 3: Множення матриць
1. Задані дві матриці `A` і `B`розмірностями 3x2 та 2х3. Виконайте їхнє множення, щоб отримати матрицю 2x2. Виведіть результуючу матрицю `result_matrix` на екран.

2. Заданий вектор `C` розмірністю 2х1. Подумайте спочатку, яку розмірність Ви отрмаєте, коли домножите `result_matrix` на вектор `C` і який результат буде. А потім виконайте множення і виведіть результат на екран.

3. Задана матриця `D` розмірністю 2х2. Подумайте спочатку, яку розмірність Ви отрмаєте, коли домножите `result_matrix` на матрицю `D` і який результат буде. А потім виконайте множення і виведіть результат на екран.

In [14]:
A = np.array(
    [[0.18, 0.53],
     [0.75, 0.47],
     [0.35, 0.21]])

B = np.array(
    [[0.17, 0.58, 0.75],
     [0.38, 0.11, 0.15]])

C = np.array([[0], [1]])

D = np.array([[0,1], [1,0]])

display(A, B, C, D)

array([[0.18, 0.53],
       [0.75, 0.47],
       [0.35, 0.21]])

array([[0.17, 0.58, 0.75],
       [0.38, 0.11, 0.15]])

array([[0],
       [1]])

array([[0, 1],
       [1, 0]])

### HW
Щоб від множення матриць А і В розмірностями 3х2 і 2х3 отримати матрицю 2х2 треба множити В на А:

In [15]:
result_matrix = np.dot(B, A)
result_matrix

array([[0.7281, 0.5202],
       [0.2034, 0.2846]])

In [16]:
C = np.array([[0], [1]])
result_vector = np.dot(result_matrix, C)
result_vector, result_vector.shape

(array([[0.5202],
        [0.2846]]),
 (2, 1))

In [17]:
result = np.dot(result_matrix, D)
result

array([[0.5202, 0.7281],
       [0.2846, 0.2034]])


### Завдання 4: Транспонування матриць
1. Транспонуйте `result_matrix`.
2. Зробіть транспонування вектора `vector` і виведіть форму нової структури. Чи бачите ви зміну?
3. Використайте операцію `numpy.expand_dims` над вектором `vector` з аргументом axis=1. Запишіть отриманий результат в змінну `column_vector` і виведіть на екран. Порівняйте з `vector`.
4. Зробіть транспонування `column_vector`, виведіть результат на екран разом з розмірностями отриманої структури.




In [18]:
result_matrix.T

array([[0.7281, 0.2034],
       [0.5202, 0.2846]])

In [19]:
vector_rand.T, vector_rand.T.shape

(array([0.83388667, 0.63979008, 0.40158324, 0.23699772, 0.09817857,
        0.05411366, 0.68022847, 0.87726471, 0.53101839, 0.7445003 ]),
 (10,))

In [20]:
vector_rand, vector_rand.shape

(array([0.83388667, 0.63979008, 0.40158324, 0.23699772, 0.09817857,
        0.05411366, 0.68022847, 0.87726471, 0.53101839, 0.7445003 ]),
 (10,))

In [21]:
transposed_vector = np.transpose(vector_rand)
transposed_vector, transposed_vector.shape

(array([0.83388667, 0.63979008, 0.40158324, 0.23699772, 0.09817857,
        0.05411366, 0.68022847, 0.87726471, 0.53101839, 0.7445003 ]),
 (10,))

In [22]:
column_vector = np.expand_dims(vector_rand, axis=1)
column_vector, column_vector.shape

(array([[0.83388667],
        [0.63979008],
        [0.40158324],
        [0.23699772],
        [0.09817857],
        [0.05411366],
        [0.68022847],
        [0.87726471],
        [0.53101839],
        [0.7445003 ]]),
 (10, 1))

In [23]:
trans_vector = np.transpose(column_vector)
trans_vector, trans_vector.shape

(array([[0.83388667, 0.63979008, 0.40158324, 0.23699772, 0.09817857,
         0.05411366, 0.68022847, 0.87726471, 0.53101839, 0.7445003 ]]),
 (1, 10))

In [24]:
column_vector.T, column_vector.T.shape

(array([[0.83388667, 0.63979008, 0.40158324, 0.23699772, 0.09817857,
         0.05411366, 0.68022847, 0.87726471, 0.53101839, 0.7445003 ]]),
 (1, 10))